[build]
  command = "next build" # Remove `next export`
  publish = "out" # This remains as the static output folder
  functions = "netlify/functions"

[dev]
  command = "next dev"
  framework = "next"
  targetPort = 3000
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[context.production]
  command = "next build"