[build]
  command = "next build && next export"
  publish = "out"
  functions = "netlify/functions"

[dev]
  command = "next dev"
  framework = "next"
  targetPort = 3000
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[context.production]
  command = "next build && next export"