[build]
  command = "next build && (pkill -f node || true)"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NETLIFY_USE_YARN = "true"
  NEXT_TELEMETRY_DISABLED = "1"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[dev]
  command = "next dev"
  framework = "next"
  targetPort = 3000
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-sitemap"