[build]
  command = "next build" # NO next export
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "next dev"
  framework = "next"
  targetPort = 3000
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-sitemap"