[build]
  command = "npm run netlify-build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NETLIFY_USE_YARN = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_IGNORE_ESLINT = "1"
  NEXT_WEBPACK_MEMORY_LIMIT = "4096"
  CI = "true"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[dev]
  command = "next dev"
  framework = "next"
  targetPort = 3000
  publish = ".next"

# We removed the problematic redirect rule that was sending all traffic to index.html
# This allows the Next.js router to handle routes properly

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
package = "netlify-plugin-cache-nextjs"